"""Add KYC fields to User

Revision ID: 10791b02b1d3
Revises: 0feca2111024
Create Date: 2026-01-19 13:21:13.555205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10791b02b1d3'
down_revision: Union[str, Sequence[str], None] = '0feca2111024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    kyc_status_enum = sa.Enum('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='kycstatus')
    kyc_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('kyc_status', kyc_status_enum, nullable=False, server_default='PENDING'))
    op.add_column('user', sa.Column('kyc_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kyc_document_url')
    op.drop_column('user', 'kyc_status')
    kyc_status_enum = sa.Enum('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='kycstatus')
    kyc_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
