"""Add location driver info and pickup location

Revision ID: 979304d97a94
Revises: 10791b02b1d3
Create Date: 2026-01-21 13:51:38.098726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '979304d97a94'
down_revision: Union[str, Sequence[str], None] = '10791b02b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('vehicle', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('vehicle', sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('driver_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'driver_contact')
    op.drop_column('vehicle', 'driver_name')
    op.drop_column('vehicle', 'location')
    op.drop_column('booking', 'pickup_location')
    # ### end Alembic commands ###
